name: Check

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  setup:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: |
          ./.github/check.sh
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
