name: Check

on: pull_request

jobs:
  setup:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: ./.github/check.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
