name: Check

on:
  push:
    branches-ignore:
      - "dependabot/*"
  pull_request:

jobs:
  steps:
    setup:
      name: Check
      runs-on: ubuntu-latest
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "pull_number=${pull_number}";
        gh pr view ${pull_number} --json