name: Check

on: pull_request

jobs:
  setup:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "pull_number=${pull_number}";
          # gh pr view ${pull_number} --json files -q '.files'
          gh api repos/Figma-Linux/figma-linux-themes/pulls/${pull_number}/files -q '.[] | [.status,.filename,.content]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
