name: Check

on: pull_request

jobs:
  setup:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "pull_number=${pull_number}";
          files=$(gh pr view ${pull_number} --json files -q '".files[].path"')

          for file in ${files}; do
            if [[ "$file" =~ \.json$ ]]; then
              echo "$file was changed"
              # gh api repos/Figma-Linux/figma-linux-themes/contents/PATH
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
